export const TransactionEventType = {
  AUTHORIZATION_TRANSACTION_PROCESSED: 'AUTHORIZATION_TRANSACTION_PROCESSED',
  CLEARING_TRANSACTION_PROCESSED: 'CLEARING_TRANSACTION_PROCESSED',
  AUTHORIZATION_EVENT_HANDLED: 'AUTHORIZATION_EVENT_HANDLED',
  CLEARING_EVENT_HANDLED: 'CLEARING_EVENT_HANDLED',
  CARDHOLDER_NOTIFIED: 'CARDHOLDER_NOTIFIED',
  ANALYTICS_SENT: 'ANALYTICS_SENT',
} as const;

export type TransactionEventType = (typeof TransactionEventType)[keyof typeof TransactionEventType];
